<?php

return [
    'DEFAULT_FILE_ICON' => 'bi-file-earmark',
    'images' => ["jpg", "jpeg", "png", "gif", "svg", "webp", "ico"],
    'icons' => [
        "aac" => "bi-filetype-aac",
        "ai" => "bi-filetype-ai",
        "bmp" => "bi-filetype-bmp",
        "cs" => "bi-filetype-cs",
        "css" => "bi-filetype-css",
        "csv" => "bi-filetype-csv",
        "doc" => "bi-filetype-doc",
        "docx" => "bi-filetype-docx",
        "exe" => "bi-filetype-exe",
        "gif" => "bi-filetype-gif",
        "heic" => "bi-filetype-heic",
        "html" => "bi-filetype-html",
        "java" => "bi-filetype-java",
        "jpg" => "bi-filetype-jpg",
        "jpeg" => "bi-filetype-jpg",
        "js" => "bi-filetype-js",
        "json" => "bi-filetype-json",
        "jsx" => "bi-filetype-jsx",
        "key" => "bi-filetype-key",
        "m4p" => "bi-filetype-m4p",
        "md" => "bi-filetype-md",
        "mid" => "bi-file-earmark-music",
        "mkv" => "bi-file-earmark-play",
        "mov" => "bi-filetype-mov",
        "mp3" => "bi-filetype-mp3",
        "mp4" => "bi-filetype-mp4",
        "otf" => "bi-filetype-otf",
        "pdf" => "bi-filetype-pdf",
        "php" => "bi-filetype-php",
        "png" => "bi-filetype-png",
        "ppt" => "bi-filetype-ppt",
        "pptx" => "bi-filetype-pptx",
        "psd" => "bi-filetype-psd",
        "py" => "bi-filetype-py",
        "raw" => "bi-filetype-raw",
        "rb" => "bi-filetype-rb",
        "rtf" => "bi-file-earmark-text",
        "sass" => "bi-filetype-sass",
        "scss" => "bi-filetype-scss",
        "sh" => "bi-filetype-sh",
        "sql" => "bi-filetype-sql",
        "svg" => "bi-filetype-svg",
        "tar" => "bi-file-zip",
        "ttf" => "bi-filetype-ttf",
        "txt" => "bi-filetype-txt",
        "wav" => "bi-filetype-wav",
        "woff" => "bi-filetype-woff",
        "xls" => "bi-filetype-xls",
        "xlsx" => "bi-filetype-xlsx",
        "xml" => "bi-filetype-xml",
        "yml" => "bi-filetype-yml",
        "zip" => "bi-file-earmark-zip",
        "rar" => "bi-file-zip-fill"
    ],

];
